#Update
version: '3.3'

services:
  app:
    container_name: nodejs_app_v2
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: authism_birge
    volumes:
      - ../stories:/stories
    networks:
      - my_custom_network

networks:
  my_custom_network:
    external: true




# version: '3.8'

# services:
      
#   app:
#     container_name: nodejs_app_v2
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_USER: root
#       DATABASE_PASSWORD: root
#       DATABASE_NAME: authism_birge
#     volumes:
#       - ./uploads:/uploads
# volumes:
#   db_data:  




# version: '3.8'

# services:
#   db:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "8082:80"
#     depends_on:
#       - db
      
#   app:
#     container_name: nodejs_app_v2
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: db
#       DATABASE_USER: root
#       DATABASE_PASSWORD: root
#       DATABASE_NAME: authism_birge
#     volumes:
#       - ./uploads:/uploads

# volumes:
#   db_data:  




# version: '3.8'

# services:
#   db:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "8082:80"
#     depends_on:
#       - db
      
#   app:
#     container_name: nodejs_app_v2
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: db
#       DATABASE_USER: root
#       DATABASE_PASSWORD: root
#       DATABASE_NAME: authism_birge

# volumes:
#   db_data:  

# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: db # Указание на то, что база данных находится в службе db
#       # Другие переменные окружения, которые может потребовать ваше приложение
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: authism_birge
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     ports:
#       - "3306:3306" # Открытие порта MySQL, если вам нужно подключаться к нему с хост-машины
#     volumes:
#       - db_data:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - "8081:80"
#     environment:
#       PMA_HOST: db
#       PMA_USER: root
#       PMA_PASSWORD: root
#       UPLOAD_LIMIT: 200M
#     depends_on:
#       - db

# volumes:
#   db_data:

# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_HOST: db
#       # Другие переменные окружения
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: authism_birge
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - "8081:80"
#     environment:
#       PMA_HOST: db
#       PMA_USER: root
#       PMA_PASSWORD: root
#       UPLOAD_LIMIT: 200M
#     depends_on:
#       - db

# volumes:
#   db_data: